
services:
  deepseek:
    image: vllm/vllm-openai:latest
    container_name: deepseek
    ports:
      - "8000:8000"
    command: >
      --model mistralai/Mistral-7B-Instruct-v0.1
      --max-model-len 2048
      --port 8000
    environment:
      - HF_TOKEN=${HF_TOKEN}  # Optional if model is public
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
