services:
  oss20b:
    image: vllm/vllm-openai:latest
    container_name: gptoss20b
    ports:
      - "8000:8000"
    command: >
      --model openai/gpt-oss-20b
      --max-model-len 128k
      --port 8000
    environment:
      - HF_TOKEN=${HF_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
