
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    networks:
      - internal
    ports:
      - "5678:5678"
    environment:
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - GENERIC_TIMEZONE=America/Los_Angeles
      - N8N_PROTOCOL=http
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678
      # optional but recommended for creds at rest:
      # - N8N_ENCRYPTION_KEY=<32+ char random string>
    volumes:
      - /mnt/c/Docker/n8n-data:/home/node/.n8n
    restart: unless-stopped


  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: miniio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - internal
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    command: server /data --console-address ":9001"
    volumes:
      - /home/narfa/docker-data/minio:/data



  kokoro-tts:
    image: ghcr.io/remsky/kokoro-fastapi-gpu:v0.2.2
    container_name: kokoro-tts
    ports:
      - "8880:8880"
    # Uncomment if GPU is available
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]

  baserow:
    image: baserow/baserow:1.32.5
    container_name: baserow
    ports:
      - "85:80"
      - "443:443"
    environment:
      - BASEROW_PUBLIC_URL=http://host.docker.internal:85
    volumes:
    - /home/narfa/docker-data/baserow:/baserow/data
    restart: unless-stopped
    shm_size: "256mb"


  stable-diffusion:
    build:
      context: ./stable_diffusion
      dockerfile: Dockerfile
    container_name: sd
    command: ["bash", "webui.sh", "--xformers", "--api", "--listen"]
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./sd-data/models:/app/stable-diffusion-webui/models
      - ./sd-data/outputs:/app/stable-diffusion-webui/outputs
      - ./sd-data/extensions:/app/stable-diffusion-webui/extensions
    restart: unless-stopped


  nca-toolkit:
    image: stephengpope/no-code-architects-toolkit:latest
    container_name: nca-toolkit
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY}
      - S3_ENDPOINT_URL=http://host.docker.internal:9000
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=nca-toolkit
      - S3_REGION=None

networks:
  internal:
    driver: bridge