
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    build:
      context: ./n8n
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    environment:
      - WEBHOOK_URL=http://host.docker.internal:5678
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    volumes:
      - C:/Docker/n8n-data:/home/node/.n8n
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: miniio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    command: server /data --console-address ":9001"
    volumes:
      - C:/Docker/minio-data:/data

  kokoro-tts:
    image: ghcr.io/remsky/kokoro-fastapi-gpu:v0.2.2
    container_name: kokoro-tts
    ports:
      - "8880:8880"
    # Uncomment if GPU is available
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [gpu]

  baserow:
    image: baserow/baserow:1.32.5
    container_name: baserow
    ports:
      - "85:80"
      - "443:443"
    environment:
      - BASEROW_PUBLIC_URL=http://host.docker.internal:85
    volumes:
      - C:/Docker/baserow-data:/baserow/data
    restart: unless-stopped
    shm_size: "256mb"


  stable-diffusion:
    build:
      context: ./stable_diffusion
      dockerfile: Dockerfile
    container_name: sd
    command: ["bash", "webui.sh", "--xformers", "--api", "--listen"]
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./models:/app/stable-diffusion-webui/models
      - ./outputs:/app/stable-diffusion-webui/outputs
    restart: unless-stopped


  nca-toolkit:
    image: stephengpope/no-code-architects-toolkit:latest
    container_name: nca-toolkit
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY}
      - S3_ENDPOINT_URL=http://host.docker.internal:9000
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=nca-toolkit
      - S3_REGION=None
